feat: TypeScript rewrite.
thenativeweb/roboter pull request #632
Opened 2021-06-16 15:13 UTC by yeldiRium

This has become a bit too huge.

BREAKING CHANGE:

- Rename the `analyse` command to `analyze`
- Add package-json linting
- Remove the `update` command
- Remove the feature to run npm scripts via the roboter
- Remove the node version check from the `deps` command
- Redesign license check configuration and behavior to give the responsibility for license compatibility to the project owner(s)
- Redesign the pre/post script running in tests
- Add watch mode for tests
- Add parameter to filter the executed tests
- Add option not to bail after failing tests

Internal things:
- Use Node.js APIs of tools wherever possible (tsc, mocha, eslint, npm-package-json-lint)
- Full typescript rewrite
- Redesign the roboter tests. Now faster and more readable
- Use the roboter to analyse and test itself

This PR is ready for review. **I'd like to get at least two reviews before merging, since this is a large PR.**

2021-07-26 09:10 UTC, goloroden requested changes
Hey @yeldiRium 👋 

First of all – congratulations to the almost finished new version of roboter, I think it looks pretty good and very promising, and the code base is oh-so-much better and more readable than ever before. Great job 🎉

I have read the code so far (I skipped the tests TBH), and I found only a few minor things. Maybe you can have a look at the comments?

2021-07-26 09:10 UTC, goloroden commented on lib/utils/fileExists.ts
> +import fs from 'fs';
I think we do have pretty much the same file as `lib/files/fileExists.ts`. Am I missing anything here?

2021-07-26 09:15 UTC, yeldiRium commented on README.md
> +To adjust the rules to be used, add an [`.npmpackagejsonlintrc.json`]() file to the root directory of your module or application. You may [extend](https://npmpackagejsonlint.org/docs/en/configuration
Regarding the link: I just forgot to paste the actual link xD

2021-07-26 09:21 UTC, yeldiRium commented on lib/utils/fileExists.ts
> +import fs from 'fs';
Yes, and I intended to delete the one at `lib/files/fileExists`, since all the other `files` related things were removed and I wanted to move this to `utils`. So the one that is obsolete is actually the one at `lib/files/fileExists` :D

2021-07-26 09:23 UTC, yeldiRium commented on lib/cli/RootOptions.ts
> +  'no-bail': boolean;
It should, but it is also necessary for the `qa` command, which is run on the root level.

2021-07-26 10:51 UTC, goloroden commented on lib/cli/RootOptions.ts
> +  'no-bail': boolean;
I see … since `qa` is the default command … okay, then I guess that's the correct implementation 👍

2021-07-27 15:34 UTC, dotKuro commented on lib/cli/RootOptions.ts
> +  version: boolean;
Why is `version` a boolean option?

2021-07-27 15:34 UTC, dotKuro commented on lib/cli/RootOptions.ts
> +  verbose: boolean;
maybe `isVerbose`?

2021-07-27 15:34 UTC, dotKuro commented on configuration/packageLicenses.ts
> +const packageLicenses: Partial<Record<string, Partial<Record<string, string>>>> = {
Sorry I don't understand the usage of `Partial` here? What happens if I access an entry of this partial record? Do I get something of `T | undefined` instead always something of type `T` then? If so, this kinda looks like a hack to me, but it might be the right way to archive this. This is just not how I am used to see `Partial` used.

2021-07-27 15:34 UTC, dotKuro commented on lib/cli/analyse/AnalyseOptions.ts
> +type AnalyseOptions = RootOptions;
Maybe `AnalyzeOptions`

2021-07-27 15:34 UTC, dotKuro commented on lib/cli/analyse/AnalyseOptions.ts
> +  AnalyseOptions
Same here

2021-07-27 15:34 UTC, dotKuro commented on lib/cli/analyse/analyseCommand.ts
> +import { AnalyseOptions } from './AnalyseOptions';
Again this file would need some changes if we would agree on analyze.

2021-07-27 15:34 UTC, dotKuro commented on lib/cli/deps/DepsOptions.ts
> +type DepsOptions = RootOptions;
Do we really want to abbreviate here?

2021-07-27 15:34 UTC, dotKuro commented on lib/utils/getSubDirectoryNames.ts
> +    filter((dirent): boolean => dirent.isDirectory()).
What does `dirent` stand for?

2021-07-27 19:25 UTC, goloroden commented on README.md
>  ## The `analyse` task
Good catch… I actually dislike the version with `z`, but this is just due to my personal idea of aesthetics. So, I agree that we should probably change this (or, offer both versions).

2021-07-27 19:26 UTC, goloroden commented on lib/cli/RootOptions.ts
> +  verbose: boolean;
Although I generally agree with you, but here, `verbose` is a CLI flag, and `roboter --verbose` makes more sense IMHO than `roboter --is-verbose`😉

2021-07-27 19:27 UTC, goloroden commented on lib/cli/deps/DepsOptions.ts
> +type DepsOptions = RootOptions;
Again, this is because there is the `roboter deps` command. It would be cumbersome to have to type `roboter dependencies` on the command-line every time, that's why we went with `deps` here.

2021-07-27 19:27 UTC, goloroden commented on lib/utils/getSubDirectoryNames.ts
> +    filter((dirent): boolean => dirent.isDirectory()).
`directory entry`, but maybe we should just call it `entry` instead of `dirent`?

2021-08-02 11:50 UTC, yeldiRium commented on lib/cli/RootOptions.ts
> +  version: boolean;
Because the `--version` flag makes the CLI just output its version and nothing else. This could be moved to a dedicated subcommand, but many CLI programs have a `--version` flag for this purpose and I think it is the first place for people to look.

2021-08-02 11:51 UTC, yeldiRium commented on configuration/packageLicenses.ts
> +const packageLicenses: Partial<Record<string, Partial<Record<string, string>>>> = {
It does exactly what you say. And agreed, `Record<string, undefined | ...>` is probably a better and even more readable option.

2021-08-02 11:53 UTC, yeldiRium commented on lib/utils/getSubDirectoryNames.ts
> +    filter((dirent): boolean => dirent.isDirectory()).
i'll take the best of both worlds and go with `directoryEntry` ;)

2021-08-02 12:53 UTC, dotKuro commented on lib/cli/RootOptions.ts
> +  verbose: boolean;
I didnt realize these are cli options...

2021-08-02 15:50 UTC, goloroden submitted a review, later dismissed

2021-08-04 11:58 UTC, goloroden approved these changes

2021-08-04 12:07 UTC, merged