fix: perform type check during `qa` command
thenativeweb/roboter pull request #708
Opened 2021-09-01 13:53 UTC by strangedev

The roboter has many commands, the default command is `qa`. This command is used in CI and locally as the standard way to perform quality assurance. It _should_ identify all problems that can be found by static analysis and report them.

The current version does not build Typescript during the `qa` command, causing type errors to be unreported. This PR adds type checking using the TypeScript compiler to the `qa` command. No code is generated during this phase.

2021-09-01 13:57 UTC, yeldiRium approved these changes

2021-09-01 14:32 UTC, goloroden requested changes

2021-09-01 14:32 UTC, goloroden commented on test/shared/fixtures/analyze/with-type-errors/src/index.ts
> +const schmarrn = add('left', 'right');
Although I like this, I don't think we should use it, since it is understandable for non-German speakers.

2021-09-03 11:45 UTC, goloroden approved these changes

2021-09-03 11:45 UTC, merged